/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface ScrollsnapControls {
        /**
          * Experimental: When set, the component will toggle aria attributes on the scrollsnap elements. This can be helpful to screenreaders but scenarios vary.
         */
        "aria": boolean;
        /**
          * Optional: Specify a character or markup for the "current" page indicator dot.
         */
        "currentDot": string | (() => void);
        /**
          * Readonly: Attribute to surface the index of the current page.
         */
        "currentIndex": number;
        /**
          * Optional: Specify a character or markup for an indicator dot.
         */
        "dot": string | (() => void);
        /**
          * Required: id or CSS selector for your scrollsnap element.
         */
        "htmlFor": string;
        /**
          * Experimental: When set, the component will attempt better paging of the scrollsnap using the ← → arrow keys.
         */
        "keys": boolean;
        /**
          * Optional: id or CSS selector for your "Next" button.
         */
        "next": string;
        /**
          * Optional: When set, the component will fetch polyfills for browsers that do not support smoothscroll natively. (Eg Safari, Edge, IE11)
         */
        "polyfill": boolean;
        /**
          * Optional: id or CSS selector for your "Previous" button.
         */
        "prev": string;
    }
}
declare global {
    interface HTMLScrollsnapControlsElement extends Components.ScrollsnapControls, HTMLStencilElement {
    }
    var HTMLScrollsnapControlsElement: {
        prototype: HTMLScrollsnapControlsElement;
        new (): HTMLScrollsnapControlsElement;
    };
    interface HTMLElementTagNameMap {
        "scrollsnap-controls": HTMLScrollsnapControlsElement;
    }
}
declare namespace LocalJSX {
    interface ScrollsnapControls {
        /**
          * Experimental: When set, the component will toggle aria attributes on the scrollsnap elements. This can be helpful to screenreaders but scenarios vary.
         */
        "aria"?: boolean;
        /**
          * Optional: Specify a character or markup for the "current" page indicator dot.
         */
        "currentDot"?: string | (() => void);
        /**
          * Readonly: Attribute to surface the index of the current page.
         */
        "currentIndex"?: number;
        /**
          * Optional: Specify a character or markup for an indicator dot.
         */
        "dot"?: string | (() => void);
        /**
          * Required: id or CSS selector for your scrollsnap element.
         */
        "htmlFor": string;
        /**
          * Experimental: When set, the component will attempt better paging of the scrollsnap using the ← → arrow keys.
         */
        "keys"?: boolean;
        /**
          * Optional: id or CSS selector for your "Next" button.
         */
        "next"?: string;
        /**
          * Optional: When set, the component will fetch polyfills for browsers that do not support smoothscroll natively. (Eg Safari, Edge, IE11)
         */
        "polyfill"?: boolean;
        /**
          * Optional: id or CSS selector for your "Previous" button.
         */
        "prev"?: string;
    }
    interface IntrinsicElements {
        "scrollsnap-controls": ScrollsnapControls;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "scrollsnap-controls": LocalJSX.ScrollsnapControls & JSXBase.HTMLAttributes<HTMLScrollsnapControlsElement>;
        }
    }
}
